# Site wide configuration

title: RandomDev
locale: pt_BR
description: De tudo um pouco sobre o mundo do desenvolvimento de software.
logo:
search: true
url: 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Robson Bittencourt
  avatar: perfil.jpg
  email: robson.luizv@gmail.com
  disqus-shortname: rbittencourt
  twitter: rluizv
  facebook: robson.bittencourt2
  github: robsonbittencourt
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: robsonbittencourt
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: RobsonBittencourt
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: